### ISSUE TITLE
When switching from second view the header is opened in first view

### ISSUE THREAD

**Issue by Aukstkalnis** [ryzngard/header-source-switch#2]
This is bad functionality. Also, when switching back to source, the source is opened in first view. So after this we have 2 views with the same file. 
The same behavior when ALT+O from the third view.

**Comment by ryzngard** [comment]
I just did a rewrite with some updated functionality. I know this issue is really old, but I'll see about getting this into the 1.1.0 release. 

Tentatively thinking the following behavior:

ALT+O always opens in current window.
ALT+SHIFT+O opens based on the following logic:

1. If not split screen, splits to the right (or down) 
2. If split screen, opens by default 1 to the right. If the current pane is the right most, then opens one left.

**Comment by jacobdufault** [comment]
It'd be really nice if `alt+shift+o` (or some additional command) operated like 'Open in other split', ie, if you have two splits and you're in the left one, open in the right split. If you're in the right split, open in the left split.

> ALT+O always opens in current window.

This will be a really great improvement! Thanks!

**Comment by ryzngard** [comment]
I forgot to close this after fixing, but this should be fixed. Let me know if this isn't working correctly

**Comment by JesseRiemens** [comment]
I would actually expect alt-shift-o to switch to the first window, when the second is selected. So when in left-right mode and one is selected, always switch to the other. 
Now it looks like when the right of two panes is selected, it creates a third and puts it there. 
Is this something that could be added please?
