### ISSUE TITLE
Exclude directories during search

### ISSUE THREAD

**Issue by BotellaA** [ryzngard/header-source-switch#8]
I would love to have some settings to restrict the file search here (https://github.com/ryzngard/header-source-switch/blob/master/src/fileOperations.ts#L89) or to validate the path later.

**Comment by ryzngard** [comment]
Sure! Is there something you had in mind for how you would set this? 

I can think of a few ways: 

* add a command to ignore current path
* have a setting with blob paths

Since this uses the vscode workspace, excluding folders from there should also restrict them from being found by this extension. It's be under Settings > Text Editor > Files

**Comment by BotellaA** [comment]
I did not know about workspace settings to excllude some directories. It should be enough for me. 
But if  have to choose between your propositions, I would prefer a setting with the correct paths (defaulted to the workspace setting).
